version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build -c Release
      - run:
          name: Test
          command: dotnet test
      - run:
          name: Build Images
          command: |
            docker build -t SimpleGenericPatterns .
            
