version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
      - image: mcr.microsoft.com/dotnet/aspnet:5.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: SimpleGenericPattern
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: SimpleGenericPattern
      - run:
          name: Test
          command: dotnet test
          working_directory: SimpleGenericPattern
      - run:
          name: Build Images
          command: |
            docker build -t SimpleGenericPatterns .
            
